kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: netbox-postgres-pvc
  namespace: netbox-community
  labels:
    app: netbox-postgres
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi