apiVersion: v1
kind: Service
metadata:
  name: netbox-postgres
  namespace: netbox-community
  labels:
    app: netbox-postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: netbox-postgres
  type: ClusterIP
