apiVersion: v1
kind: ConfigMap
metadata:
  name: netbox-configmap
  namespace: netbox-community
data:
  # NetBox environment variables
  # More configuration can be added via: https://netbox.readthedocs.io/en/stable/configuration/optional-settings/
  ALLOWED_HOST: '*'
  TZ: Austria/Vienna
  DB_HOST: netbox-postgres
  DB_PORT: "5432"
  DB_NAME: netbox
  DB_USER: netbox

  MEDIA_ROOT: /opt/netbox/netbox/media
  METRICS_ENABLED: "true"
  REDIS_HOST: redis
  REDIS_PORT:  "6379"
  REDIS_DB_TASK:  "0"
  REDIS_DB_CACHE: "1"
